### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jimthedev** [vernonk/patternguide#2]
Hi Vernon,

This looks really interesting. Would an example implementation of a sample app using pattern guide be something that you would consider including or keeping in a separate repo?

**Comment by vernonk** [comment]
First... thanks! Most definitely. I hope to include some base components to show how the whole thing comes together over the next few weeks. June 15th is the date I have for myself to have the first version of the living style guide portion ready. That will require a few examples of things regardless (base elements, components, patterns, layouts) so that will be awesome.

**Comment by jimthedev** [comment]
Fantastic. If you need a second set of eyes closer to that date to QA/review, let me know.

**Comment by vernonk** [comment]
I will definitely reach out to you. Thanks a ton!
